/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack.presentacion;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Label;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pack.logica.EstadoJugar;
import pack.logica.EstrategiaComplica;
import pack.logica.EstrategiaGravedad;
import pack.logica.EstrategiaNormal;
import pack.logica.JuegoComplica;
import pack.logica.JuegoGravedad;
import pack.logica.JuegoNormal;
import pack.logica.TableroNormal;
import pack.modelo.Tablero;
import pack.vista.TableroGrafico;

/**
 *
 * @author daniel
 */
public class PanelMenu extends javax.swing.JPanel {
    private final ArrayList<JFrame> vistasAux = new ArrayList<>();
    /**
     * Creates new form PanelMenu
     */
    public PanelMenu() {
        initComponents();
        crear();
        desfocarTodo();
    }
    
    private void crear() {
        Cursor mano = new Cursor(Cursor.HAND_CURSOR);
        butonJugar.setCursor(mano);
        radioJEA.setCursor(mano);
        radioGravedad.setCursor(mano);
        radioComplica.setCursor(mano);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoJuego = new javax.swing.ButtonGroup();
        radioJEA = new javax.swing.JRadioButton();
        radioGravedad = new javax.swing.JRadioButton();
        butonJugar = new javax.swing.JButton();
        radioComplica = new javax.swing.JRadioButton();
        butonTerminar = new javax.swing.JButton();
        spinnerVistas = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        butonVistas = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));
        setPreferredSize(new java.awt.Dimension(316, 53));

        grupoJuego.add(radioJEA);
        radioJEA.setText("Normal");
        radioJEA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioJEAMouseClicked(evt);
            }
        });

        grupoJuego.add(radioGravedad);
        radioGravedad.setText("Gravedad");
        radioGravedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioGravedadMouseClicked(evt);
            }
        });

        butonJugar.setIcon(new javax.swing.ImageIcon("/home/daniel/NetBeansProjects/4_Linea/img/png/001-boton-de-reproduccion.png")); // NOI18N
        butonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonJugarActionPerformed(evt);
            }
        });

        grupoJuego.add(radioComplica);
        radioComplica.setText("Complica");
        radioComplica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioComplicaMouseClicked(evt);
            }
        });

        butonTerminar.setIcon(new javax.swing.ImageIcon("/home/daniel/NetBeansProjects/4_Linea/img/png/002-flechas-senal-triangular-de-reciclaje.png")); // NOI18N
        butonTerminar.setEnabled(false);
        butonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonTerminarActionPerformed(evt);
            }
        });

        spinnerVistas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        jLabel1.setText("Vistas:");

        butonVistas.setIcon(new javax.swing.ImageIcon("/home/daniel/NetBeansProjects/4_Linea/img/png/003-ojo.png")); // NOI18N
        butonVistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonVistasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioJEA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioGravedad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioComplica))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerVistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butonJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(butonVistas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioJEA)
                    .addComponent(radioGravedad)
                    .addComponent(butonJugar)
                    .addComponent(radioComplica)
                    .addComponent(butonTerminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerVistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(butonVistas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonJugarActionPerformed
        // TODO add your handling code here:
        try {
            if (grupoJuego.getSelection().equals(radioJEA.getModel())) {
                Tablero _tablero = new TableroNormal(new EstrategiaNormal(), new int[7][6]);
                Main._juego = new JuegoNormal(_tablero);
                Main._juego.iniciarJuego(new EstadoJugar());
                radioGravedad.setEnabled(false);
                crearVistas(_tablero);
            }
            else if (grupoJuego.getSelection().equals(radioGravedad.getModel())) {
                Tablero _tablero = new TableroNormal(new EstrategiaGravedad(), new int[7][6]);
                Main._juego = new JuegoGravedad(_tablero);
                Main._juego.iniciarJuego(new EstadoJugar());
                radioJEA.setEnabled(false);
                radioComplica.setEnabled(false);
                crearVistas(_tablero);
            }
            else if (grupoJuego.getSelection().equals(radioComplica.getModel())) {
                Tablero _tablero = new TableroNormal(new EstrategiaComplica(), new int[6][4]);
                Main._juego = new JuegoComplica(_tablero);
                Main._juego.iniciarJuego(new EstadoJugar());
                radioGravedad.setEnabled(false);
                crearVistas(_tablero);
            }
            spinnerVistas.setEnabled(false);
            butonJugar.setEnabled(false);
            butonTerminar.setEnabled(true);
            Main._frame.pack();
        }
        catch (NullPointerException ex) {
            JOptionPane.showConfirmDialog(this, "Selecciona un juego", "OJO", JOptionPane.CLOSED_OPTION);
        }
    }//GEN-LAST:event_butonJugarActionPerformed

    private void radioJEAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioJEAMouseClicked
        // TODO add your handling code here:
        if (Main._juego != null)
            Main._juego.getTablero().setEstrategia(new EstrategiaNormal());
    }//GEN-LAST:event_radioJEAMouseClicked

    private void radioGravedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioGravedadMouseClicked
        // TODO add your handling code here:
        if (Main._juego != null)
            Main._juego.getTablero().setEstrategia(new EstrategiaGravedad());
    }//GEN-LAST:event_radioGravedadMouseClicked

    private void radioComplicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioComplicaMouseClicked
        // TODO add your handling code here:
        if (Main._juego != null)
            Main._juego.getTablero().setEstrategia(new EstrategiaComplica());
    }//GEN-LAST:event_radioComplicaMouseClicked

    private void butonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonTerminarActionPerformed
        // TODO add your handling code here:
        spinnerVistas.setEnabled(true);
        radioJEA.setEnabled(true);
        radioGravedad.setEnabled(true);
        radioComplica.setEnabled(true);
        butonJugar.setEnabled(true);
        butonTerminar.setEnabled(false);
        Main._frame.getContentPane().remove(1);
        Main._juego = null;
        Main._frame.pack();
        for (JFrame jFrame : vistasAux)
            jFrame.dispose();
        vistasAux.removeAll(vistasAux);
    }//GEN-LAST:event_butonTerminarActionPerformed

    private void butonVistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonVistasActionPerformed
        // TODO add your handling code here:
        for (JFrame jFrame : vistasAux) {
            if (!jFrame.isVisible())
                jFrame.setVisible(true);
        }
    }//GEN-LAST:event_butonVistasActionPerformed

    private void crearVistas(Tablero _tablero) {
        for (int i = 0; i < Integer.parseInt(spinnerVistas.getValue().toString()); i++) {
            TableroGrafico _tableroGrafico = new Tablero1(_tablero);
            _tableroGrafico.requestFocus();
            
            if (i == 0) {
                _tableroGrafico.setPreferredSize(new Dimension(_tablero.getGrilla()[0].length * 60 + 2, _tablero.getGrilla().length * 60 + 32));
                Main._frame.getContentPane().add(_tableroGrafico, BorderLayout.CENTER);
            }
            else {
                _tableroGrafico.setPreferredSize(new Dimension(_tablero.getGrilla()[0].length * 60 + 16, _tablero.getGrilla().length * 60 + 34));
                JFrame frame = new JFrame("Vista " + i);
                frame.add(_tableroGrafico);
                frame.pack();
                frame.setVisible(true);
                vistasAux.add(frame);
            }
            Main._juego.agregarObservador(_tableroGrafico);
        }
    }
    
    private void desfocarTodo() {
        butonJugar.setFocusable(false);
        butonTerminar.setFocusable(false);
        butonVistas.setFocusable(false);
        radioJEA.setFocusable(false);
        radioGravedad.setFocusable(false);
        radioComplica.setFocusable(false);
        spinnerVistas.setFocusable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonJugar;
    private javax.swing.JButton butonTerminar;
    private javax.swing.JButton butonVistas;
    private javax.swing.ButtonGroup grupoJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton radioComplica;
    private javax.swing.JRadioButton radioGravedad;
    private javax.swing.JRadioButton radioJEA;
    private javax.swing.JSpinner spinnerVistas;
    // End of variables declaration//GEN-END:variables
    
}
